version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: myroom
      MYSQL_USER: myroom
      MYSQL_PASSWORD: 0000
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  elasticsearch_data:
    driver: local
  mysql_data:
    driver: local

#docker-compose up --build



#docker exec -it mysql mysql -u root -p

#docker exec -it mysql mysql -u devquest -p
#devquest1234

#use devquest;
