spring:
  application:
    name: devQuest
  profiles:
    include: s3
  datasource:
    url: jdbc:mysql://localhost:3307/myroom?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&allowMultiQueries=true&createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: myroom
    password: 0000
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      location: C:/uploads/
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

springdoc:
  swagger-ui:
    persistAuthorization: true
    tryItOutEnabled: true